In [1]:
%pip install pandas openpyxl

  Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 2.8 MB/s eta 0:00:05
   - -------------------------------------- 0.5/12.6 MB 2.8 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/12.6 MB 1.8 MB/s eta 0:00:07
   ---- ----------------------------------- 1.6/12.6 MB 2.0 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.6 MB 1.8 MB/s eta 0:00:06
   ------- -------------------------------- 2.4/12.6 MB 2.0 MB/s eta 0:00:06
   -------- ------------------------------- 2.6/12.6 MB 1.8 MB/s eta 0:00:06
   --------- ------------------------------ 2.9/12.6 MB 1.6 MB/s eta 0:00:06
   --------- ------------------------------ 3.1/


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [16]:
import numpy as np
import pandas as pd

df=pd.read_excel("basic_odd_even_dataset.xlsx")
df_array=df.to_numpy()
X=df_array[:,0]
y=df_array[:,1]
y

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [39]:
X=X.reshape(-1, 1)
y=y.reshape(-1, 1)

In [41]:
input_size=1
hidden_size=2
output_size=1


#initialize weights and bias
np.random.seed(42)
W1=np.random.randn(input_size,hidden_size)*0.01
b1=np.zeros((1,hidden_size))
W2=np.random.randn(hidden_size,output_size)*0.01
b2=np.zeros((1,output_size))

In [42]:
X.shape

(10, 1)

In [ ]:
#activation functions
def relu(z):
    return np.maximum(0,z)
def relu_derivative(z):
    return z>0

def sigmoid(z):
    return 1/(1+np.exp(-z))
def sigmoid_derivative(A):
    return A*(1-A)

In [44]:
def forward_pass(x,W1,b1,W2,b2):
    Z1=np.dot(x,W1)+b1
    A1=relu(Z1)
    Z2=np.dot(A1,W2)+b2
    A2=sigmoid(Z2)
    return Z1,A1,Z2,A2

In [45]:
y.shape[0]

10

In [46]:
def compute_loss(y_true,y_pred):
    m=y_true.shape[0]
    #we are using binary loss entropy as loss function
    loss=-np.sum((y_true*np.log(y_pred))+((1-y_true)*np.log(1-y_pred)))/m
    return loss

In [47]:
def back_propagation(X,y,Z1,A1,Z2,A2,W1,W2):
    m=X.shape[0]

    #output layer gradients
    dz2=A2-y
    dw2=(np.dot(A1.T,dz2))/m
    db2=np.sum(dz2, axis=0, keepdims=True)/m

    #hidden layer gradients
    dA1=np.dot(dz2,W2.T)
    dz1=dA1*relu_derivative(Z1)
    dw1=(np.dot(X.T,dz1))/m
    db1=np.sum(dz1, axis=0, keepdims=True)/m

    return dw1,db1,dw2,db2

In [48]:
def update_weights_and_bias(W1,b1,W2,b2,dw1,db1,dw2,db2,learning_rate):
    W1=W1-(learning_rate*dw1)
    b1=b1-(learning_rate*db1)
    W2=W2-(learning_rate*dw2)
    b2=b2-(learning_rate*db2)

    return W1,b1,W2,b2

In [58]:
# training loop
learning_rate=0.01
epochs=10
print("initial: ",W1,b1,W2,b2)
for epoch in range(epochs):
    
    Z1,A1,Z2,A2=forward_pass(X,W1,b1,W2,b2)
    # print("forward:",A1,A2)
    loss=compute_loss(y,A2)
    dw1,db1,dw2,db2=back_propagation(X,A2,Z1,A1,Z2,A2,W1,W2)
    print("gradients:",dw1,db1,dw2,db2)
    W1,b1,W2,b2=update_weights_and_bias(W1,b1,W2,b2,dw1,db1,dw2,db2,learning_rate)
    # Print loss every 100 epochs
    # if epoch % 100 == 0:
    print(W1,b1,W2,b2)
    print(f"Epoch {epoch}, Loss: {loss}")

initial:  [[ 0.00496714 -0.00138264]] [[0. 0.]] [[0.00647689]
 [0.0152303 ]] [[0.]]
gradients: [[0. 0.]] [[0. 0.]] [[0.]
 [0.]] [[0.]]
[[ 0.00496714 -0.00138264]] [[0. 0.]] [[0.00647689]
 [0.0152303 ]] [[0.]]
Epoch 0, Loss: 0.693139141345586
gradients: [[0. 0.]] [[0. 0.]] [[0.]
 [0.]] [[0.]]
[[ 0.00496714 -0.00138264]] [[0. 0.]] [[0.00647689]
 [0.0152303 ]] [[0.]]
Epoch 1, Loss: 0.693139141345586
gradients: [[0. 0.]] [[0. 0.]] [[0.]
 [0.]] [[0.]]
[[ 0.00496714 -0.00138264]] [[0. 0.]] [[0.00647689]
 [0.0152303 ]] [[0.]]
Epoch 2, Loss: 0.693139141345586
gradients: [[0. 0.]] [[0. 0.]] [[0.]
 [0.]] [[0.]]
[[ 0.00496714 -0.00138264]] [[0. 0.]] [[0.00647689]
 [0.0152303 ]] [[0.]]
Epoch 3, Loss: 0.693139141345586
gradients: [[0. 0.]] [[0. 0.]] [[0.]
 [0.]] [[0.]]
[[ 0.00496714 -0.00138264]] [[0. 0.]] [[0.00647689]
 [0.0152303 ]] [[0.]]
Epoch 4, Loss: 0.693139141345586
gradients: [[0. 0.]] [[0. 0.]] [[0.]
 [0.]] [[0.]]
[[ 0.00496714 -0.00138264]] [[0. 0.]] [[0.00647689]
 [0.0152303 ]] [[0.]]
E

In [52]:
def predict(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_pass(X, W1, b1, W2, b2)
    return (A2 > 0.5).astype(int)

predictions = predict(X, W1, b1, W2, b2)
print("Predictions:", predictions.flatten())

Predictions: [0 1 1 1 1 1 1 1 1 1]
